"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from core.env import (
    load_env_file,
    get_env,
    get_env_bool,
    get_env_int,
    get_env_list,
)

load_env_file()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _resolve_path(raw_path):
    path = Path(raw_path)
    if path.is_absolute():
        return path
    return BASE_DIR / raw_path


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env("DJANGO_SECRET_KEY", required=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool("DJANGO_DEBUG", required=True)

ALLOWED_HOSTS = get_env_list("DJANGO_ALLOWED_HOSTS", required=True)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rag'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_engine = get_env("DJANGO_DB_ENGINE", required=True)
_db_name = get_env("DJANGO_DB_NAME", required=True)
DATABASES = {
    "default": {
        "ENGINE": _db_engine,
        "NAME": _resolve_path(_db_name),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = get_env("DJANGO_LANGUAGE_CODE", required=True)

TIME_ZONE = get_env("DJANGO_TIME_ZONE", required=True)

USE_I18N = get_env_bool("DJANGO_USE_I18N", required=True)

USE_TZ = get_env_bool("DJANGO_USE_TZ", required=True)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = get_env("DJANGO_STATIC_URL", required=True)
_static_dirs = get_env_list("DJANGO_STATICFILES_DIRS", required=True)
STATICFILES_DIRS = [_resolve_path(path) for path in _static_dirs]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = get_env("DJANGO_DEFAULT_AUTO_FIELD", required=True)

# Đường dẫn file được upload
MEDIA_URL = get_env("DJANGO_MEDIA_URL", required=True)
MEDIA_ROOT = _resolve_path(get_env("DJANGO_MEDIA_ROOT", required=True))

# Giới hạn kích thước upload (50MB + overhead)
DATA_UPLOAD_MAX_MEMORY_SIZE = get_env_int("DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE", required=True)
FILE_UPLOAD_MAX_MEMORY_SIZE = get_env_int("DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE", required=True)

SMARTDOC_UI_CONFIG = {
    "requestTimeoutMs": get_env_int("SMARTDOC_UI_REQUEST_TIMEOUT_MS", required=True),
    "streamIdleTimeoutMs": get_env_int("SMARTDOC_UI_STREAM_IDLE_TIMEOUT_MS", required=True),
    "textareaMaxHeight": get_env_int("SMARTDOC_UI_TEXTAREA_MAX_HEIGHT", required=True),
    "toastDurationMs": get_env_int("SMARTDOC_UI_TOAST_DURATION_MS", required=True),
    "toastExitMs": get_env_int("SMARTDOC_UI_TOAST_EXIT_MS", required=True),
    "uploadReloadDelayMs": get_env_int("SMARTDOC_UI_UPLOAD_RELOAD_DELAY_MS", required=True),
    "statusClearDelayMs": get_env_int("SMARTDOC_UI_STATUS_CLEAR_DELAY_MS", required=True),
    "deleteRedirectDelayMs": get_env_int("SMARTDOC_UI_DELETE_REDIRECT_DELAY_MS", required=True),
}
