# Generated by Django 5.2.12 on 2026-04-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding_model',
            field=models.CharField(blank=True, choices=[('nomic-embed-text-v2-moe', 'nomic-embed-text-v2-moe'), ('qwen3-embedding:0.6b', 'qwen3-embedding:0.6b'), ('nomic-embed-text', 'nomic-embed-text'), ('bge-m3:567m', 'bge-m3:567m')], max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size_mb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='has_vietnamese',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='vector_db_key',
            field=models.CharField(blank=True, choices=[('qwen_db', 'qwen_db'), ('bge_db', 'bge_db'), ('nomic_v2_db', 'nomic_v2_db'), ('nomic_v1_db', 'nomic_v1_db')], max_length=32),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='rag.document'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='embedding_model',
            field=models.CharField(blank=True, choices=[('nomic-embed-text-v2-moe', 'nomic-embed-text-v2-moe'), ('qwen3-embedding:0.6b', 'qwen3-embedding:0.6b'), ('nomic-embed-text', 'nomic-embed-text'), ('bge-m3:567m', 'bge-m3:567m')], max_length=64),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='llm_model',
            field=models.CharField(choices=[('gemma4:e4b', 'gemma4:e4b'), ('gemma4:e2b', 'gemma4:e2b'), ('qwen3.5:2b', 'qwen3.5:2b'), ('qwen3.5:4b', 'qwen3.5:4b'), ('qwen3.5:9b', 'qwen3.5:9b')], default='gemma4:e4b', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='vector_db_key',
            field=models.CharField(blank=True, choices=[('qwen_db', 'qwen_db'), ('bge_db', 'bge_db'), ('nomic_v2_db', 'nomic_v2_db'), ('nomic_v1_db', 'nomic_v1_db')], max_length=32),
        ),
    ]
