# Generated by Django 5.2.12 on 2026-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_document_and_session_routing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embed_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='embed_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='embed_status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='document',
            name='embed_step',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
