# Generated by Django 5.2.12 on 2026-04-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_document_and_session_routing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, help_text='Tóm tắt nội dung chính của hội thoại')),
                ('key_facts', models.TextField(blank=True, help_text='JSON: Các sự kiện, thông tin quan trọng')),
                ('user_preferences', models.TextField(blank=True, help_text='JSON: Tùy chọn, sở thích người dùng')),
                ('memory_type', models.CharField(choices=[('summary', 'Tóm tắt hội thoại'), ('facts', 'Sự kiện quan trọng'), ('preferences', 'Tùy chọn người dùng')], default='summary', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='rag.chatsession')),
            ],
            options={
                'verbose_name': 'Conversation Memory',
                'verbose_name_plural': 'Conversation Memories',
            },
        ),
        migrations.CreateModel(
            name='MemoryIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('semantic', 'Semantic Memory - Kiến thức chung'), ('episodic', 'Episodic Memory - Hội thoại cụ thể'), ('procedural', 'Procedural Memory - Quy trình, cách làm')], default='semantic', max_length=20)),
                ('embedding_model', models.CharField(choices=[('nomic-embed-text-v2-moe', 'nomic-embed-text-v2-moe'), ('qwen3-embedding:0.6b', 'qwen3-embedding:0.6b'), ('nomic-embed-text', 'nomic-embed-text'), ('bge-m3:567m', 'bge-m3:567m')], max_length=64)),
                ('vector_db_key', models.CharField(choices=[('qwen_db', 'qwen_db'), ('bge_db', 'bge_db'), ('nomic_v2_db', 'nomic_v2_db'), ('nomic_v1_db', 'nomic_v1_db')], max_length=32)),
                ('is_indexed', models.BooleanField(default=False)),
                ('chunk_count', models.IntegerField(default=0, help_text='Số lượng memory chunks đã index')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_indices', to='rag.document')),
            ],
            options={
                'verbose_name': 'Memory Index',
                'verbose_name_plural': 'Memory Indices',
                'unique_together': {('document', 'memory_type')},
            },
        ),
    ]
