# Generated by Django 5.2.12 on 2026-04-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_memory_augmented_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('general', 'Chat thường - Không dùng RAG'), ('rag', 'RAG - Có tài liệu ngữ cảnh')], default='general', max_length=20),
        ),
    ]
