# Generated by Django 5.2.12 on 2026-04-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_chatsession_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='llm_model',
            field=models.CharField(choices=[('gemma4:e2b', 'gemma4:e2b'), ('gemma4:e4b', 'gemma4:e4b'), ('qwen3.5:2b', 'qwen3.5:2b'), ('qwen3.5:4b', 'qwen3.5:4b'), ('qwen3.5:9b', 'qwen3.5:9b')], default='gemma4:e2b', max_length=50),
        ),
    ]
