# Generated by Django 5.2.12 on 2026-04-29

import json
from pathlib import Path
from django.conf import settings
from django.db import migrations, models


def import_user_info_json(apps, schema_editor):
    user_info_path = Path(settings.BASE_DIR) / "user_info.json"
    if not user_info_path.exists():
        return

    try:
        with user_info_path.open("r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except Exception:
        return

    users = payload.get("users") if isinstance(payload, dict) else None
    if not isinstance(users, dict):
        return

    UserProfile = apps.get_model("rag", "UserProfile")
    for session_key, profile_data in users.items():
        if not session_key or not isinstance(profile_data, dict):
            continue

        name = profile_data.get("name")
        age = profile_data.get("age")
        preferences = profile_data.get("preferences")

        if not isinstance(name, str):
            name = ""
        if not isinstance(age, int) or age <= 0 or age > 120:
            age = None
        if not isinstance(preferences, list):
            preferences = []

        cleaned_preferences = [
            item.strip() for item in preferences
            if isinstance(item, str) and item.strip()
        ][:8]

        UserProfile.objects.update_or_create(
            session_key=session_key,
            defaults={
                "name": name[:60],
                "age": age,
                "preferences": cleaned_preferences,
            },
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0005_alter_chatsession_llm_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(blank=True, max_length=60)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("preferences", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.RunPython(import_user_info_json, noop_reverse),
    ]
