# Generated by Django 5.2.12 on 2026-05-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='embedding_model',
            field=models.CharField(blank=True, choices=[('nomic-embed-text', 'nomic-embed-text')], max_length=64),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='llm_model',
            field=models.CharField(choices=[('ibm/granite4.1:8b-q8_0', 'ibm/granite4.1:8b-q8_0'), ('gemma4:e4b', 'gemma4:e4b'), ('gemma4:e2b', 'gemma4:e2b')], default='ibm/granite4.1:8b-q8_0', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='vector_db_key',
            field=models.CharField(blank=True, choices=[('nomic_v1_db', 'nomic_v1_db')], max_length=32),
        ),
        migrations.AlterField(
            model_name='document',
            name='embedding_model',
            field=models.CharField(blank=True, choices=[('nomic-embed-text', 'nomic-embed-text')], max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='vector_db_key',
            field=models.CharField(blank=True, choices=[('nomic_v1_db', 'nomic_v1_db')], max_length=32),
        ),
        migrations.AlterField(
            model_name='memoryindex',
            name='embedding_model',
            field=models.CharField(choices=[('nomic-embed-text', 'nomic-embed-text')], max_length=64),
        ),
        migrations.AlterField(
            model_name='memoryindex',
            name='vector_db_key',
            field=models.CharField(choices=[('nomic_v1_db', 'nomic_v1_db')], max_length=32),
        ),
    ]
