# Generated by Django 5.2.12 on 2026-05-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0007_alter_chatsession_embedding_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='llm_model',
            field=models.CharField(choices=[('qcwind/qwen2.5-7B-instruct-Q4_K_M', 'qcwind/qwen2.5-7B-instruct-Q4_K_M'), ('ibm/granite4.1:8b-q8_0', 'ibm/granite4.1:8b-q8_0'), ('gemma4:e4b', 'gemma4:e4b'), ('gemma4:e2b', 'gemma4:e2b')], default='qcwind/qwen2.5-7B-instruct-Q4_K_M', max_length=50),
        ),
    ]
